### PR TITLE
Bcnode now allows proper usage of external miner

### PR DESCRIPTION
**Pull request by iamklob**
I've added all necessary changes to remove the need for rebuilding / patching the `blockcollider/bcnode` image. I will merge these soon to bcnode - and this PR makes it usable directly with the GPU miner

### CODE REVIEW

**Comment by lgray** [comment]
Did you duct tape PM to the ceiling or something? Why the sudden acceptance of semi-open-sourceyness?

We'll pick up the changes with the next image push, trick runs a bot so no need for a PR - thanks for incorporating this stuff.

Having a preview of changes is nice.

**Comment by lgray** [comment]
Ah - sorry thought this was bc-src. Anyway that'll pick it up and we can merge this. TY.

**Comment by iamklob** [comment]
> Ah - sorry thought this was bc-src. Anyway that'll pick it up and we can merge this. TY.

Oh, now I understand, good :-)

**Comment by iamklob** [comment]
I've just pushed new `blockcollider/bcnode:latest` with the appropriate changes, so if you agree, this can be merged.

**Comment by neo-root** [comment]
Any instruction how to connect an external miner? Is it possible to connect olminer?

**Pull request merged**
